### ISSUE TITLE
Live Chat (livechatinc.com) breaking with turbolinks

### ISSUE THREAD

**Issue by maddijoyce** [reed/turbolinks-compatibility#21]
Hey,

Livechat provides this code:

``` javascript
var __lc = {};
__lc.license = 3989411;

(function() {
    var lc = document.createElement('script'); lc.type = 'text/javascript'; lc.async = true;
    lc.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'cdn.livechatinc.com/tracking.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(lc, s);
})();
```

to drop inside a script tag inside your body.

At the moment, I can see it on the first page, but I lose it once turbolinks runs. I tried it inside a function that runs on page:load but get errors with that as well. I'll keep trying but any help you could give would be great.

**Comment by snehawatharkar** [comment]
I keep getting "Script Error" on loading my site. What might be the reason and wat might fix it?

**Comment by maddijoyce** [comment]
Do you have a bit more info? Is "Script Error" a console error or just straight in the website? Can you include the javascript that's causing the error?

**Comment by bizappay** [comment]
I'm getting a warning message @ console saying that like attached. Hence the live chat won't appear at my website. 
![Screenshot-6](https://user-images.githubusercontent.com/51228858/58692546-651f7d00-83c1-11e9-8122-3b4f5693f727.png)

**Comment by faiberr** [comment]
Hi, I tried that solution and it actually works, but throw this errors on the console: 
![image](https://user-images.githubusercontent.com/69908910/98734850-8fc08400-2370-11eb-869a-aa1c4742a602.png)

Any thoughts?

**Comment by faiberr** [comment]
I leave this approach here, maybe is useful to somebody else:

This code loads the script widget in all pages, but in some pages Turbolinks replaces the DOM, loosing the HTML for rendering the widget.

We use `LivechatWidget.call('destroy')` to kill the widget and then call the function that bring it back on those cases, that's why we use those 2 event listeners. And the property `data-turbolinks-eval="false"` on the script tag is important.

![image](https://user-images.githubusercontent.com/69908910/98863100-dd52f480-2435-11eb-904d-82cdfd9626be.png)
