### ISSUE TITLE
Google Universal analytics in head

### ISSUE THREAD

**Issue by allaire** [reed/turbolinks-compatibility#54]
Hi @reed,

In this article: http://reed.github.io/turbolinks-compatibility/google_universal_analytics.html it is recommended to place the code right under the opening `<body>` tag. However, now google suggests to place it right above the closing `</head>` tag: https://developers.google.com/analytics/devguides/collection/analyticsjs/

_To begin tracking a website using analytics.js, paste the following JavaScript snippet into your website templates so that it appears before the closing </head> tag._

I tried to move it there, but now Google does not track anymore the page change (at least in the real time view in Google Analytics).

My question is, isn't having the snippet in the `<head>` section the same as having the code in the `<body>` section with `data-turbolinks-eval="false"`? Technically, both will only be loaded once no?

Thanks!

**Comment by allaire** [comment]
Maybe @rmarescu @michellekaye @jdibella could give their input since they seem to be in the contributor list! :beers:

**Comment by rmarescu** [comment]
With [Turbolinks](https://github.com/rails/turbolinks), the page is loaded once, and only the body and page title are changed on subsequent requests.

I believe you should be able to move the first script tag from the solution to `<head>` section (no need for `data-turbolinks-eval` attribute anymore), but you must keep the `set` and `send` in the body, so that are triggered with every request (haven't tested it though).
So it would look something like this:

```HTML
<!doctype html>
<html>
  <head>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-123456-1', 'auto');
    </script>
  </head>
  <body>
    <script>
      ga('set', 'location', location.href.split('#')[0]);
      ga('send', 'pageview', { "title": document.title });
    </script>
  </body>
</html>
```

The reason why the solution recommends keeping both in `<body>` is for integration purposes (you don't have to split up your code into multiple partials or complicate your logic)
Google [recommends](https://groups.google.com/d/msg/digital-analytics-fundamentals/V9z4TVXQW_4/OgW6M9xJLqAJ) having it in the `<head>` for better tracking in some situations.

Having it just below `<body>` tag when using Turbolinks I think is a good compromise.

**Comment by allaire** [comment]
@rmarescu This makes total sense, thanks!

I'm also about to integrate another tracking code (HotJar: http://inside.hotjar.com/support/solutions/articles/1000125978-installing-hotjar-on-your-website-manually).

Do you have any tips to detect how I should integrate this particular code with Turbolinks? Currently I integrated it just like Google Analytics (under the `<body` tag, with `<script data-turbolinks-eval="false">`), like this:

```
<script data-turbolinks-eval="false">
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-28393670-2', 'auto');
</script>
<script>
  ga('set', 'location', location.href.split('#')[0]);
  ga('send', 'pageview', { "title": document.title });
</script>

<!-- Hotjar Tracking Code for www.agendrix.com -->
<script data-turbolinks-eval="false">
    (function(f,b){
        var c;
        f.hj=f.hj||function(){(f.hj.q=f.hj.q||[]).push(arguments)};
        f._hjSettings={hjid:18465, hjsv:4};
        c=b.createElement("script");c.async=1;
        c.src="//static.hotjar.com/c/hotjar-"+f._hjSettings.hjid+".js?sv="+f._hjSettings.hjsv;
        b.getElementsByTagName("head")[0].appendChild(c);
    })(window,document);
</script>
```

**Comment by jdibella** [comment]
The HotJar implementation appears to be inserting a `<script>` tag element into the document head to do tracking, so the tracking code script insertion will execute once with the `data-turbolinks-eval` attribute set.  Since the contents of the `<head>` tag are *not* refreshed on page load, if the actual HotJar implementation requires the inserted script tag to be executed on every page request, you won't see expected results.

If the script tag needs to be executed for every page request, you'd need to check if the inserted `<script> ` tag is present in the the `<head>`, remove it, and re-add it, to force script execution on every page.

**Comment by allaire** [comment]
@jdibella or simply add it in the `<body>` without `data-turbolinks-eval` ?

**Comment by jdibella** [comment]
The danger there is that it would add another `<script>` tag to the head on every page request. If a user visits 3 pages, that would result in 3 `<script>` tags being present in the document `<head>`. Depending on how the HotJar implemention is written, this could produce conflicts.

**Comment by bitcoder** [comment]
@jdibella and @allaire , so what you suggest on this?
i'm adding it to the body but i'm not sure if it messes due to inserting the same script reference in the head more than once...

**Comment by allaire** [comment]
@bitcoder Hey,

I'm adding it inside the `<body>` as well with a `data-turbolinks-eval="false"` on the google `<script>` tag.

Have a nice day

**Comment by bitcoder** [comment]
thanks @allaire
